const STATUS_IDLE = "IDLE";
const STATUS_STARTING = "STARTING";
const STATUS_RUNNING = "RUNNING";

const TYPE_CONSOMMATEUR = "CONSOMMATEUR";
const TYPE_PRODUCTEUR = "PRODUCTEUR";

const MSG_INIT = "INIT";
const MSG_LINK = "LINK";
const MSG_REQ = "REQ";
const MSG_REL = "REL";
const MSG_ACK = "ACK";
const MSG_BESOIN_SC = "ASK_SC";
const MSG_FIN_SC = "END_SC";
const MSG_MAJ = "MAJ";
const MSG_DEB_SC = "START_SC";

module.exports = {
  STATUS_IDLE,
  STATUS_STARTING,
  STATUS_RUNNING,
  TYPE_CONSOMMATEUR,
  TYPE_PRODUCTEUR,
  MSG_INIT,
  MSG_LINK,
  MSG_REQ,
  MSG_REL,
  MSG_ACK,
  MSG_BESOIN_SC,
  MSG_FIN_SC,
  MSG_MAJ,
  MSG_DEB_SC,
};
